{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ default (include "workload.fullname" .) .Values.configMap.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "workload.labels" . | nindent 4 }}
{{- if .Values.configMap.data }}
data:
  {{- toYaml .Values.configMap.data | nindent 2 }}
{{- else }}
data: {}
{{- end }}
{{- end }}
