{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "workload.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "workload.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    {{- include "workload.selectorLabels" . | nindent 4 }}
  ports:
    - name: {{ .Values.service.name | default "http" }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default .Values.containerPort }}
      protocol: TCP
    {{- if .Values.metrics.enabled }}
    - name: {{ .Values.metrics.name | default "metrics" }}
      port: {{ .Values.metrics.port | default 4195 }}
      targetPort: {{ .Values.metrics.port | default 4195 }}
      protocol: TCP
    {{- end }}
    {{- with .Values.service.extraPorts }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
