{{- range $app, $files := .Values.apps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Values.configMaps }}-{{ $app }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: sample-apps
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    helm.sh/chart: {{ printf "%s-%s" $.Chart.Name $.Chart.Version }}
data:
  {{- toYaml $files | nindent 2 }}
{{- end }}
