apiVersion: joinedcontext.com/v1alpha1
kind: Policy
metadata:
  name: public-events
  namespace: helsinki
  title: { en: "Public read: events" }
spec:
  contextSpaceRef: { kind: ContextSpace, name: helsinki }
  assigner: did:web:{orgDomain}
  assignee: { kind: role, id: public }
  operations: [retrieveOps]
  information:
    - entities:
        - type: Event
